//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trax
{
    using System;
    using System.Collections.Generic;
    
    public partial class Json
    {
        public int Id { get; set; }
        public string JsonData { get; set; }
        public string Name { get; set; }
    }
}
